CREATE TABLE publishers (
    email CHARACTER VARYING(20) DEFAULT null PRIMARY KEY,
    name CHARACTER VARYING(50) NOT NULL,
    address CHARACTER VARYING(50) DEFAULT null,
    bank_account CHARACTER VARYING(20) NOT NULL
);
