CREATE TABLE genres (
    name CHARACTER VARYING(20) DEFAULT null PRIMARY KEY,
    description CHARACTER VARYING(100) DEFAULT null
);
CREATE TABLE authors (
    id INT DEFAULT null PRIMARY KEY,
    bio CHARACTER VARYING(100) DEFAULT null,
    nationality CHARACTER VARYING(20) NOT NULL,
    fname CHARACTER VARYING(20) NOT NULL,
    lname CHARACTER VARYING(20) NOT NULL,
    dob DATE NOT NULL
);
