ALTER TABLE authors ALTER COLUMN id DROP NOT NULL;
ALTER TABLE billing_infos ALTER COLUMN id DROP NOT NULL;
ALTER TABLE books DROP COLUMN isbn;
ALTER TABLE books ADD COLUMN isbn UUID NOT NULL;
ALTER TABLE checkout_baskets ALTER COLUMN email DROP NOT NULL;
ALTER TABLE genres ALTER COLUMN name DROP NOT NULL;
ALTER TABLE in_basket ALTER COLUMN email DROP NOT NULL;
ALTER TABLE is_genre ALTER COLUMN name DROP NOT NULL;
ALTER TABLE ordered ALTER COLUMN isbn DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN id DROP NOT NULL;
ALTER TABLE publishers ALTER COLUMN email DROP NOT NULL;
ALTER TABLE shipping_infos ALTER COLUMN id DROP NOT NULL;
ALTER TABLE tracking_infos ALTER COLUMN id DROP NOT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE wrote ALTER COLUMN aid DROP NOT NULL;
ALTER TABLE billing_infos DROP CONSTRAINT billing_infos_id_fkey;
ALTER TABLE checkout_baskets DROP CONSTRAINT checkout_baskets_email_fkey;
ALTER TABLE in_basket DROP CONSTRAINT in_basket_email_fkey;
ALTER TABLE in_basket DROP CONSTRAINT in_basket_isbn_fkey;
ALTER TABLE is_genre DROP CONSTRAINT is_genre_isbn_fkey;
ALTER TABLE is_genre DROP CONSTRAINT is_genre_name_fkey;
ALTER TABLE ordered DROP CONSTRAINT ordered_isbn_fkey;
ALTER TABLE ordered DROP CONSTRAINT ordered_onum_fkey;
ALTER TABLE orders DROP CONSTRAINT orders_email_fkey;
ALTER TABLE shipping_infos DROP CONSTRAINT shipping_infos_id_fkey;
ALTER TABLE tracking_infos DROP CONSTRAINT tracking_infos_id_fkey;
ALTER TABLE wrote DROP CONSTRAINT wrote_aid_fkey;
ALTER TABLE wrote DROP CONSTRAINT wrote_isbn_fkey;
