ALTER TABLE authors ALTER COLUMN id DROP NOT NULL;
ALTER TABLE billing_infos ALTER COLUMN order_number DROP NOT NULL;
ALTER TABLE books ALTER COLUMN isbn DROP NOT NULL;
ALTER TABLE checkout_baskets ALTER COLUMN email DROP NOT NULL;
ALTER TABLE genres ALTER COLUMN name DROP NOT NULL;
ALTER TABLE in_basket ALTER COLUMN email DROP NOT NULL;
ALTER TABLE is_genre ALTER COLUMN genre_name DROP NOT NULL;
ALTER TABLE ordered ALTER COLUMN isbn DROP NOT NULL;
ALTER TABLE orders DROP COLUMN number;
ALTER TABLE orders ADD COLUMN order_number INT DEFAULT null;
ALTER TABLE publishers ALTER COLUMN email DROP NOT NULL;
ALTER TABLE shipping_infos ALTER COLUMN order_number DROP NOT NULL;
ALTER TABLE tracking_infos ALTER COLUMN order_number DROP NOT NULL;
ALTER TABLE users ALTER COLUMN email DROP NOT NULL;
ALTER TABLE wrote ALTER COLUMN aid DROP NOT NULL;
ALTER TABLE billing_infos DROP CONSTRAINT billing_infos_order_number_fkey;
ALTER TABLE books DROP CONSTRAINT books_p_email_fkey;
ALTER TABLE checkout_baskets DROP CONSTRAINT checkout_baskets_email_fkey;
ALTER TABLE in_basket DROP CONSTRAINT in_basket_email_fkey;
ALTER TABLE in_basket DROP CONSTRAINT in_basket_isbn_fkey;
ALTER TABLE is_genre DROP CONSTRAINT is_genre_genre_name_fkey;
ALTER TABLE is_genre DROP CONSTRAINT is_genre_isbn_fkey;
ALTER TABLE ordered DROP CONSTRAINT ordered_isbn_fkey;
ALTER TABLE ordered DROP CONSTRAINT ordered_order_number_fkey;
ALTER TABLE shipping_infos DROP CONSTRAINT shipping_infos_order_number_fkey;
ALTER TABLE tracking_infos DROP CONSTRAINT tracking_infos_order_number_fkey;
ALTER TABLE wrote DROP CONSTRAINT wrote_aid_fkey;
ALTER TABLE wrote DROP CONSTRAINT wrote_isbn_fkey;
